[package]
name = "ostree-tool"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
gvariant = "0.5.0"
hex = "0.4.3"
json = "0.12.4"
miniz_oxide = "0.6.1"
